[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Line Madsen", email = "linemeldgaard@geo.au.dk"}]
dynamic = ["version", "description"]
